name: Pull Request Reviewers
description: Add reviewers to a pull request
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client.
  reviewers:
    description: List of user logins to add as reviewers
runs:
  using: node12
  main: "main.js"
branding:
  icon: git-pull-request
  color: blue
