name: Pull Requests

on:
  push:

jobs:
  reviewers:
    runs-on: ubuntu-latest
    name: "Reviewers"
    if: github.event_name == 'pull_request' && github.event.action == 'ready_for_review'
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        working-directory: ./.github/actions/pull_requests/reviewers
      - uses: ./.github/actions/pull_requests/reviewers
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: apazzolini
